name: Test Java Proxy 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
      
      env:
        ACROLINX_API_USERNAME: ${{ secrets.TEST_SERVER_USERNAME }}
        ACROLINX_API_SSO_TOKEN: ${{ secrets.TEST_SERVER_SSO_TOKEN }}

    - name: Build proxy
      run: |
        cd java/servlet/
        mvn compile

    - name: Test proxy with Stable
      run: |
        ACROLIX_URL = ${{ secrets.TEST_SERVER_URL_STABLE }}
        ACROLINX_API_TOKEN = ${{ secrets.TEST_SERVER_API_TOKEN_STABLE }}
        cd java/servlet/
        mvn '-Dtest=com.acrolinx.*Test' test

    - name: Test proxy with 
      run: |
        ACROLIX_URL = ${{ secrets.TEST_SERVER_URL_UNSTABLE }}
        ACROLINX_API_TOKEN = ${{ secrets.TEST_SERVER_API_TOKEN_UNSTABLE }}
        cd java/servlet/
        mvn '-Dtest=com.acrolinx.*Test' test
